/* tslint:disable */
/* eslint-disable */
/**
 * Traffic API
 * This API allows CRUD operations on SUMO Traffic data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Instant
 */
export interface Instant {
    /**
     * 
     * @type {number}
     * @memberof Instant
     */
    nanos?: number;
    /**
     * 
     * @type {number}
     * @memberof Instant
     */
    seconds?: number;
    /**
     * 
     * @type {number}
     * @memberof Instant
     */
    epochSecond?: number;
    /**
     * 
     * @type {number}
     * @memberof Instant
     */
    nano?: number;
}

export function InstantFromJSON(json: any): Instant {
    return InstantFromJSONTyped(json, false);
}

export function InstantFromJSONTyped(json: any, ignoreDiscriminator: boolean): Instant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nanos': !exists(json, 'nanos') ? undefined : json['nanos'],
        'seconds': !exists(json, 'seconds') ? undefined : json['seconds'],
        'epochSecond': !exists(json, 'epochSecond') ? undefined : json['epochSecond'],
        'nano': !exists(json, 'nano') ? undefined : json['nano'],
    };
}

export function InstantToJSON(value?: Instant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nanos': value.nanos,
        'seconds': value.seconds,
        'epochSecond': value.epochSecond,
        'nano': value.nano,
    };
}


