/* tslint:disable */
/* eslint-disable */
/**
 * Public Transport API
 * This API allows CRUD operations on SUMO Traffic data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * POJO that represents a vehicle at a specific time.
 * @export
 * @interface Vehicle
 */
export interface Vehicle {
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    personCapacity?: number;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    personNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof Vehicle
     */
    speed?: number;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    time?: string;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    typeId?: string;
    /**
     * 
     * @type {string}
     * @memberof Vehicle
     */
    vehicleId?: string;
}

export function VehicleFromJSON(json: any): Vehicle {
    return VehicleFromJSONTyped(json, false);
}

export function VehicleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Vehicle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'personCapacity': !exists(json, 'personCapacity') ? undefined : json['personCapacity'],
        'personNumber': !exists(json, 'personNumber') ? undefined : json['personNumber'],
        'speed': !exists(json, 'speed') ? undefined : json['speed'],
        'time': !exists(json, 'time') ? undefined : json['time'],
        'typeId': !exists(json, 'typeId') ? undefined : json['typeId'],
        'vehicleId': !exists(json, 'vehicleId') ? undefined : json['vehicleId'],
    };
}

export function VehicleToJSON(value?: Vehicle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
        'personCapacity': value.personCapacity,
        'personNumber': value.personNumber,
        'speed': value.speed,
        'time': value.time,
        'typeId': value.typeId,
        'vehicleId': value.vehicleId,
    };
}


