/* tslint:disable */
/* eslint-disable */
/**
 * Traffic API
 * This API allows CRUD operations on SUMO Traffic data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Instant,
    InstantFromJSON,
    InstantFromJSONTyped,
    InstantToJSON,
} from './';

/**
 * 
 * @export
 * @interface VehicleDTO
 */
export interface VehicleDTO {
    /**
     * 
     * @type {number}
     * @memberof VehicleDTO
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof VehicleDTO
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof VehicleDTO
     */
    personCapacity?: number;
    /**
     * 
     * @type {number}
     * @memberof VehicleDTO
     */
    personNumber?: number;
    /**
     * 
     * @type {number}
     * @memberof VehicleDTO
     */
    speed?: number;
    /**
     * 
     * @type {Instant}
     * @memberof VehicleDTO
     */
    time?: Instant;
    /**
     * 
     * @type {string}
     * @memberof VehicleDTO
     */
    typeId?: string;
    /**
     * 
     * @type {string}
     * @memberof VehicleDTO
     */
    vehicleId?: string;
}

export function VehicleDTOFromJSON(json: any): VehicleDTO {
    return VehicleDTOFromJSONTyped(json, false);
}

export function VehicleDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): VehicleDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'latitude': !exists(json, 'latitude') ? undefined : json['latitude'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'personCapacity': !exists(json, 'personCapacity') ? undefined : json['personCapacity'],
        'personNumber': !exists(json, 'personNumber') ? undefined : json['personNumber'],
        'speed': !exists(json, 'speed') ? undefined : json['speed'],
        'time': !exists(json, 'time') ? undefined : InstantFromJSON(json['time']),
        'typeId': !exists(json, 'typeId') ? undefined : json['typeId'],
        'vehicleId': !exists(json, 'vehicleId') ? undefined : json['vehicleId'],
    };
}

export function VehicleDTOToJSON(value?: VehicleDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'latitude': value.latitude,
        'longitude': value.longitude,
        'personCapacity': value.personCapacity,
        'personNumber': value.personNumber,
        'speed': value.speed,
        'time': InstantToJSON(value.time),
        'typeId': value.typeId,
        'vehicleId': value.vehicleId,
    };
}


