/* tslint:disable */
/* eslint-disable */
/**
 * Traffic API
 * This API allows CRUD operations on SUMO Traffic data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Vehicle,
    VehicleFromJSON,
    VehicleToJSON,
} from '../models';

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async trafficVehiclesBusesSinceLastFiveMinutesGetRaw(): Promise<runtime.ApiResponse<Array<Vehicle>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/traffic/vehicles/busesSinceLastFiveMinutes`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VehicleFromJSON));
    }

    /**
     */
    async trafficVehiclesBusesSinceLastFiveMinutesGet(): Promise<Array<Vehicle>> {
        const response = await this.trafficVehiclesBusesSinceLastFiveMinutesGetRaw();
        return await response.value();
    }

    /**
     */
    async trafficVehiclesCarsSinceLastFiveSecondsGetRaw(): Promise<runtime.ApiResponse<Array<Vehicle>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/traffic/vehicles/carsSinceLastFiveSeconds`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VehicleFromJSON));
    }

    /**
     */
    async trafficVehiclesCarsSinceLastFiveSecondsGet(): Promise<Array<Vehicle>> {
        const response = await this.trafficVehiclesCarsSinceLastFiveSecondsGetRaw();
        return await response.value();
    }

}
