/* tslint:disable */
/* eslint-disable */
/**
 * Traffic API
 * This API allows CRUD operations on SUMO Traffic data
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    VehicleDTO,
    VehicleDTOFromJSON,
    VehicleDTOToJSON,
} from '../models';

/**
 * no description
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     */
    async trafficVehiclesGetRaw(): Promise<runtime.ApiResponse<Array<VehicleDTO>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/traffic/vehicles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(VehicleDTOFromJSON));
    }

    /**
     */
    async trafficVehiclesGet(): Promise<Array<VehicleDTO>> {
        const response = await this.trafficVehiclesGetRaw();
        return await response.value();
    }

}
