name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Gradle build
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
    - name: Gradle check
      uses: eskatos/gradle-command-action@v1
      with:
        arguments: check
