name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: Gradle build & test Manage Vehicle Data
        uses: eskatos/gradle-command-action@v1
        with:
          build-root-directory: ./manage-vehicle-data
          wrapper-directory: ./manage-vehicle-data
          arguments: build check
